services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - CHROMA_HOST=chromadb
      - OLLAMA_HOST=ollama
    depends_on:
      - chromadb
      - ollama
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  chromadb:
    image: chromadb/chroma
    ports:
      - "8001:8000"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  ollama_data:
